describe('Agregar proyecto', function() {
    it('Agregar proyecto', function() {
        cy.visit('https://todoist.com/app#start')
        cy.get(".standalone_page").find('input[name="email"]').click().type("tati@test.com")
        cy.get('.standalone_page').find('input[name="password"]').click().type("pruebas1234")
        cy.get('.standalone_page').find('button[class="submit_btn ist_button ist_button_red sel_login"]').click()
        cy.wait(1900)
        cy.get('div[id="left_menu"]').find('button[data-track="navigation|projects_quick_add"]').click()
        cy.get('form').find('input[id="edit_project_modal_field_name"]').click().type("Nuevo proyecto")
        cy.get('form').find('button[class="color_dropdown_toggle form_field_control"]').click()
        cy.get('div[id="dropdown-select-3-popup"]').find('li[id="dropdown-select-3-option-41"]').click()
        cy.get('form').find('div[class="form_field form_field_inline"]').click()
        cy.get('form').find('button[class="ist_button ist_button_red"]').click()
        cy.get('.left_menu').contains('Nuevo proyecto')
    })
})

describe('No agregue un proyecto sin nombre', function() {
    it('No agregue un proyecto sin nombre', function() {
      cy.visit('https://todoist.com/app#start')
      cy.get(".standalone_page").find('input[name="email"]').click().type("tati@test.com")
      cy.get('.standalone_page').find('input[name="password"]').click().type("pruebas1234")
      cy.get('.standalone_page').find('button[class="submit_btn ist_button ist_button_red sel_login"]').click()
      cy.wait(1900)
      cy.get('div[id="left_menu"]').find('button[data-track="navigation|projects_quick_add"]').click()
      cy.get('form').find('button[aria-disabled="true"]')
    })
})

describe('Editar proyecto', function() {
    it('Editar proyecto', function() {
        cy.visit('https://todoist.com/app#start')
        cy.get(".standalone_page").find('input[name="email"]').click().type("tati@test.com")
        cy.get('.standalone_page').find('input[name="password"]').click().type("pruebas1234")
        cy.get('.standalone_page').find('button[class="submit_btn ist_button ist_button_red sel_login"]').click()
        cy.wait(1900)
        cy.get('div[id="left_menu"]').find('button[data-track="navigation|projects_quick_add"]').click()
        cy.get('form').find('input[id="edit_project_modal_field_name"]').click().type("Proyecto a editar")
        cy.get('form').find('button[class="color_dropdown_toggle form_field_control"]').click()
        cy.get('div[id="dropdown-select-3-popup"]').find('li[id="dropdown-select-3-option-42"]').click()
        cy.get('form').find('button[class="ist_button ist_button_red"]').click()
        cy.contains('Proyecto a editar').click()
        cy.get('.left_menu').get('ul').children('.current').find('table[class="item_table"]').find('td[class="menu"]').click({force: true})
        cy.get('div[class="ist_menu"]').get('tr[class="project_archive_action project_inbox_action menu_item"]').find('td[data-track="projects|menu_edit"]').click({force: true})
        cy.get('form').find('input[id="edit_project_modal_field_name"]').click().type("Nombre editado")
        cy.get('div[id="dropdown-select-3-popup"]').find('li[id="dropdown-select-3-option-33"]').click()
        cy.get('button[class="ist_button ist_button_red"]').click()
        cy.get('div[id="left_menu"]').not('Proyecto a eliminar')
    })
})

describe('Eliminar proyecto', function() {
    it('Eliminar proyecto', function() {
        cy.visit('https://todoist.com/app#start')
        cy.get(".standalone_page").find('input[name="email"]').click().type("tati@test.com")
        cy.get('.standalone_page').find('input[name="password"]').click().type("pruebas1234")
        cy.get('.standalone_page').find('button[class="submit_btn ist_button ist_button_red sel_login"]').click()
        cy.wait(1900)
        cy.get('div[id="left_menu"]').find('button[data-track="navigation|projects_quick_add"]').click()
        cy.get('form').find('input[id="edit_project_modal_field_name"]').click().type("Proyecto a eliminar")
        cy.get('form').find('button[class="ist_button ist_button_red"]').click()
        cy.contains('Proyecto a eliminar').click()
        cy.get('.left_menu').get('ul').children('.current').find('table[class="item_table"]').find('td[class="menu"]').click({force: true})
        cy.get('span[id="menu_delete_text"]').click()
        cy.get('button[class="ist_button ist_button_red"]').click()
        cy.get('div[id="left_menu"]').not('Proyecto a eliminar')
    })
})
